import {useEffect,useRef} from 'react';
import * as T from 'three';
import {OrbitControls} from 'three/examples/jsm/controls/OrbitControls.js';
import {PointerTap} from './pointer-tap';
import {GROUPS,type Atlas,type ViewerState} from './fly-data';
import {CELL_GROUPS,type CellAtlas,type CellState,type Neuron} from './cell-data';

interface Props {atlas:Atlas;data:CellAtlas;state:ViewerState;cells:CellState;onSelect:(id:string)=>void;onProgress:(n:number)=>void;onError:(s:string)=>void}
export default function CellScene(props:Props){
 const host=useRef<HTMLDivElement>(null),latest=useRef(props);latest.current=props;
 useEffect(()=>{
  const el=host.current!,abort=new AbortController();let gone=false,frame=0,loaded=0,hovered:string|null=null,appearance='',viewKey='',fitting=true;
  let renderer:T.WebGLRenderer;try{renderer=new T.WebGLRenderer({antialias:true,powerPreference:'high-performance',preserveDrawingBuffer:true});}catch{props.onError('WebGL is required for the neuron viewer.');return;}
  renderer.setClearColor('#111111');renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;el.appendChild(renderer.domElement);renderer.domElement.setAttribute('aria-label','Published MaleCNS neuron reconstructions. Drag to orbit and click a neuron to inspect it.');
  const scene=new T.Scene(),camera=new T.PerspectiveCamera(34,1,.01,150),controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minDistance=.08;controls.maxDistance=65;
  scene.add(new T.HemisphereLight('#ffffff','#444444',2));const light=new T.DirectionalLight('#fff8ee',3);light.position.set(-4,8,6);scene.add(light);const rim=new T.DirectionalLight('#dbe5ff',2);rim.position.set(5,4,-6);scene.add(rim);
  const stage=new T.Group();scene.add(stage);const disk=new T.Mesh(new T.CylinderGeometry(4.65,4.72,.15,128),new T.MeshStandardMaterial({color:'#181818',roughness:.8}));disk.position.y=-.08;stage.add(disk);
  for(const r of [4.15,4.38]){const ring=new T.Mesh(new T.RingGeometry(r,r+.009,192),new T.MeshBasicMaterial({color:'#747474',side:T.DoubleSide,transparent:true,opacity:.4}));ring.rotation.x=-Math.PI/2;ring.position.y=.008;stage.add(ring);}
  const grid=new T.GridHelper(100,100,'#333333','#242424');grid.position.y=-.17;scene.add(grid);
  const bounds=new T.Box3();props.atlas.parts.forEach(p=>bounds.union(new T.Box3(new T.Vector3(...p.bounds[0]),new T.Vector3(...p.bounds[1]))));const origin=bounds.getCenter(new T.Vector3()),scale=7.2/bounds.getSize(new T.Vector3()).x;
  const groups=CELL_GROUPS.map(()=>{const g=new T.Group();scene.add(g);return g;});
  const items:{neuron:Neuron;line:T.LineSegments<T.BufferGeometry,T.LineBasicMaterial>;group:T.Group}[]=[],surfaceCache=new Map<string,T.Mesh<T.BufferGeometry,T.MeshStandardMaterial>>(),pending=new Set<string>();
  const batches:T.LineSegments<T.BufferGeometry,T.LineBasicMaterial>[]=[];
  function batchOverview(){
   for(const group of groups){
    const members=items.filter(it=>it.group===group),vertexCount=members.reduce((sum,it)=>sum+it.line.geometry.getAttribute('position').count,0),indexCount=members.reduce((sum,it)=>sum+it.line.geometry.index!.count,0);
    const position=new Float32Array(vertexCount*3),index=new Uint32Array(indexCount);let vertexOffset=0,indexOffset=0;
    for(const it of members){const g=it.line.geometry,p=g.getAttribute('position'),idx=g.index!;position.set(p.array,vertexOffset*3);for(let i=0;i<idx.count;i++)index[indexOffset+i]=idx.getX(i)+vertexOffset;vertexOffset+=p.count;indexOffset+=idx.count;}
    const geometry=new T.BufferGeometry();geometry.setAttribute('position',new T.BufferAttribute(position,3));geometry.setIndex(new T.BufferAttribute(index,1));geometry.computeBoundingSphere();
    const batch=new T.LineSegments(geometry,new T.LineBasicMaterial({color:members[0]?.line.material.color??'#b7b7b7',transparent:true,opacity:.43,depthWrite:false}));group.add(batch);batches.push(batch);
   }
   appearance='';
  }
  const load=async(path:string)=>{const r=await fetch(path,{signal:abort.signal});if(!r.ok)throw new Error(`Neuron data could not load (${r.status}).`);return r.arrayBuffer();};
  const positions=(v:DataView,n:number,offset:number)=>{const out=new Float32Array(n*3);for(let i=0;i<n;i++){out[i*3]=(v.getFloat32(offset+i*12,true)-origin.x)*scale;out[i*3+1]=2.65-(v.getFloat32(offset+i*12+4,true)-origin.y)*scale;out[i*3+2]=-(v.getFloat32(offset+i*12+8,true)-origin.z)*scale;}return out;};
  latest.current.onProgress(0);
  (async()=>{try{let cursor=0;await Promise.all(Array.from({length:8},async()=>{while(cursor<props.data.neurons.length){const n=props.data.neurons[cursor++],b=await load(`/male-cns/skeletons/${n.id}.bin`);if(gone)return;const v=new DataView(b),nv=v.getUint32(0,true),ne=v.getUint32(4,true),pos=positions(v,nv,8),idx=new Uint32Array(ne*2);for(let i=0;i<idx.length;i++)idx[i]=v.getUint32(8+nv*12+i*4,true);const g=new T.BufferGeometry();g.setAttribute('position',new T.BufferAttribute(pos,3));g.setIndex(new T.BufferAttribute(idx,1));g.computeBoundingBox();g.computeBoundingSphere();const line=new T.LineSegments(g,new T.LineBasicMaterial({color:GROUPS.find(g=>g.id===n.group)!.color,transparent:true,opacity:.75,depthWrite:false}));line.userData.id=n.id;const group=groups[CELL_GROUPS.indexOf(n.group as typeof CELL_GROUPS[number])];group.add(line);items.push({neuron:n,line,group});appearance='';viewKey='';latest.current.onProgress(Math.round(++loaded/props.data.neurons.length*100));}}));if(!gone)batchOverview();}catch(e){if(!gone)latest.current.onError(e instanceof Error?e.message:'Neuron collection could not load.');}})();
  const status=document.createElement('div');status.className='cell-surface-status';status.hidden=true;el.appendChild(status);
  async function nativeSurface(id:string){if(surfaceCache.has(id)||pending.has(id))return;pending.add(id);status.textContent='Loading native neuron surface…';status.hidden=false;try{const b=await load(`/male-cns/neurons/${id}.bin`);if(gone)return;const v=new DataView(b),n=v.getUint32(0,true),g=new T.BufferGeometry(),pos=positions(v,n,4),indices=new Uint32Array((b.byteLength-4-n*12)/4);for(let i=0;i<indices.length;i++)indices[i]=v.getUint32(4+n*12+i*4,true);g.setAttribute('position',new T.BufferAttribute(pos,3));g.setIndex(new T.BufferAttribute(indices,1));g.computeVertexNormals();g.computeBoundingBox();const mesh=new T.Mesh(g,new T.MeshStandardMaterial({color:'#d2c9ba',roughness:.45,side:T.DoubleSide}));mesh.visible=false;const neuron=props.data.neurons.find(n=>n.id===id)!;groups[CELL_GROUPS.indexOf(neuron.group as typeof CELL_GROUPS[number])].add(mesh);surfaceCache.set(id,mesh);appearance='';viewKey='';}catch(e){if(!gone){status.textContent='Surface unavailable. The traced centerline is still visible.';return;}}finally{pending.delete(id);}status.hidden=true;}
  const target=new T.Vector3(),eye=new T.Vector3();
  function fit(){const {state:s,cells:c}=latest.current;const box=new T.Box3();for(const it of items){if(c.solo?it.neuron.id===c.selected:!c.group||it.neuron.group===c.group)box.union(it.line.geometry.boundingBox!.clone().translate(it.group.position));}if(box.isEmpty())box.set(new T.Vector3(-4,.4,-2),new T.Vector3(4,5,2));const size=box.getSize(new T.Vector3());box.getCenter(target);const dist=Math.max(size.y,size.x/camera.aspect,size.z*.7,.4)/(2*Math.tan(T.MathUtils.degToRad(17)))*1.3;const dir=s.view==='posterior'?new T.Vector3(0,.05,-1):s.view==='dorsal'?new T.Vector3(0,1,.001):s.view==='lateral'?new T.Vector3(1,.1,0):new T.Vector3(.04,.05,1);eye.copy(target).addScaledVector(dir.normalize(),dist);fitting=true;}
  const resize=()=>{renderer.setSize(el.clientWidth,el.clientHeight);camera.aspect=el.clientWidth/el.clientHeight;camera.updateProjectionMatrix();fit();};const ro=new ResizeObserver(resize);ro.observe(el);controls.addEventListener('start',()=>fitting=false);
  const tooltip=document.createElement('div');tooltip.className='mesh-hover';tooltip.hidden=true;el.appendChild(tooltip);const ray=new T.Raycaster(),pointer=new T.Vector2(),tap=new PointerTap();ray.params.Line={threshold:.022};
  function hit(e:PointerEvent){const r=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);return ray.intersectObjects(items.filter(i=>i.group.visible&&(!latest.current.cells.solo||i.neuron.id===latest.current.cells.selected)).map(i=>i.line),false)[0]?.object.userData.id as string|undefined;}
  let lastHover=0;const down=(e:PointerEvent)=>tap.down(e.pointerId,e.clientX,e.clientY,6),move=(e:PointerEvent)=>{tap.move(e.pointerId,e.clientX,e.clientY);if(e.buttons||performance.now()-lastHover<150)return;lastHover=performance.now();hovered=hit(e)??null;const n=items.find(i=>i.neuron.id===hovered)?.neuron;tooltip.hidden=!n;if(n){tooltip.textContent=`${n.instance} · ${n.id}`;const r=el.getBoundingClientRect();tooltip.style.left=Math.min(el.clientWidth-220,e.clientX-r.left+12)+'px';tooltip.style.top=Math.max(10,e.clientY-r.top-36)+'px';}renderer.domElement.style.cursor=n?'pointer':'grab';};const up=(e:PointerEvent)=>{if(tap.up(e.pointerId,e.clientX,e.clientY)){const id=hit(e);if(id)latest.current.onSelect(id);}};
  renderer.domElement.addEventListener('pointerdown',down);renderer.domElement.addEventListener('pointermove',move);renderer.domElement.addEventListener('pointerup',up);renderer.domElement.addEventListener('pointercancel',e=>tap.cancel(e.pointerId));renderer.domElement.addEventListener('pointerleave',()=>{hovered=null;tooltip.hidden=true;});
  const clock=new T.Clock(),reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
  function animate(){if(gone)return;frame=requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.05),{state:s,cells:c}=latest.current;
   CELL_GROUPS.forEach((g,i)=>{groups[i].visible=!c.group||g===c.group;groups[i].position.set((i%2===0?-2.6:2.6)*s.explode,(i<2?1.6:-1.6)*s.explode,0);});
   const key=JSON.stringify([c,s.surface,s.meshLines,hovered,items.length,surfaceCache.size,batches.length]);if(key!==appearance){for(const batch of batches){batch.visible=!c.solo;batch.material.opacity=c.selected?.1:.43;}for(const it of items){const selected=it.neuron.id===c.selected,active=selected||it.neuron.id===hovered,native=selected&&c.surface&&surfaceCache.has(it.neuron.id);it.line.visible=(!c.solo||selected)&&!native&&(!batches.length||active||c.solo);it.line.material.opacity=active?1:c.selected?.13:.7;it.line.material.color.set(active?'#f3d79e':GROUPS.find(g=>g.id===it.neuron.group)!.color);}for(const [id,m]of surfaceCache){m.visible=id===c.selected&&c.surface;let wire=m.children[0] as T.LineSegments|undefined;if(m.visible&&s.meshLines&&!wire){wire=new T.LineSegments(new T.WireframeGeometry(m.geometry),new T.LineBasicMaterial({color:'#555555',transparent:true,opacity:.22,depthWrite:false}));m.add(wire);}if(wire)wire.visible=!!s.meshLines;m.material.polygonOffset=!!s.meshLines;m.material.polygonOffsetFactor=1;m.material.polygonOffsetUnits=1;m.material.color.set(s.surface==='tissue'?'#d2c9ba':GROUPS.find(g=>g.id===props.data.neurons.find(n=>n.id===id)!.group)!.color);}appearance=key;}
   if(c.surface&&c.selected&&props.data.neurons.find(n=>n.id===c.selected)?.mesh)void nativeSurface(c.selected);
   const vk=JSON.stringify([c.solo,c.solo?c.selected:null,c.group,s.view,s.reset,s.explode,items.length]);if(vk!==viewKey){fit();viewKey=vk;}
   if(fitting){camera.position.lerp(eye,reduced?1:1-Math.exp(-7*dt));controls.target.lerp(target,reduced?1:1-Math.exp(-7*dt));if(camera.position.distanceTo(eye)<.001)fitting=false;}
   stage.visible=grid.visible=!c.solo&&s.explode<.2;controls.autoRotate=s.rotate&&!reduced;controls.autoRotateSpeed=.6;controls.update();renderer.render(scene,camera);
  }
  const exportImage=()=>{const size=renderer.getSize(new T.Vector2()),ratio=renderer.getPixelRatio();renderer.setPixelRatio(1);renderer.setSize(3840,Math.round(3840/camera.aspect),false);renderer.render(scene,camera);const a=document.createElement('a');a.download='malecns-neurons-4k.png';a.href=renderer.domElement.toDataURL('image/png');a.click();renderer.setPixelRatio(ratio);renderer.setSize(size.x,size.y,false);};window.addEventListener('fly-atlas-export',exportImage);resize();animate();
  return()=>{gone=true;abort.abort();cancelAnimationFrame(frame);ro.disconnect();controls.dispose();window.removeEventListener('fly-atlas-export',exportImage);scene.traverse(o=>{if(o instanceof T.Mesh||o instanceof T.LineSegments){o.geometry.dispose();(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>m.dispose());}});renderer.dispose();renderer.domElement.remove();tooltip.remove();status.remove();};
 },[props.atlas,props.data]);
 return <div className="fly-scene" ref={host}/>;
}
