export const SOURCES = [
 {id:'malecns',title:'MaleCNS connectome · published reconstruction',authors:'Berg et al. · Cell · 2026',url:'https://research.google/pubs/sexual-dimorphism-in-the-complete-connectome-of-the-drosophila-male-central-nervous-system/',note:'The published male central nervous system reconstruction contains 166,691 neurons across the brain and ventral nerve cord. This explorer uses its brain regions and a selected 1,712-neuron collection, not the full connectome.'},
 {id:'geometry',title:'MaleCNS public geometry & downloads',authors:'MaleCNS · v1.0 / fullbrain-roi-v5 · CC BY 4.0',url:'https://male-cns.janelia.org/download/',note:'80 brain-region surfaces preserve 7,270,902 native triangles. CV-anterior and CRN entries are excluded from the brain-region inventory. Neuron centerlines and eight native neuron surfaces share the same EM coordinate space. Data files are attributed and checksum-verified.'},
 {id:'ito',title:'A systematic nomenclature for the insect brain',authors:'Ito et al. · Neuron · 2014',url:'https://doi.org/10.1016/j.neuron.2013.12.017',note:'The anatomical naming framework for neuropils. A neuropil is a region rich in neuronal processes and synapses; it is not a separate organ with a hard capsule.'},
 {id:'annotation',title:'Male CNS cell type explorer',authors:'MaleCNS project · published cell annotations',url:'https://reiserlab.github.io/celltype-explorer-drosophila-male-cns/',note:'The source catalogue of annotated neuron types and morphology. Type and instance names are preserved in the cellular view. The selected collection is intended for visual exploration and is not a representative sample.'},
 {id:'repository',title:'malecns · programmatic access to MaleCNS',authors:'natverse / Janelia FlyEM / Cambridge · GPL-3.0 code',url:'https://github.com/natverse/malecns',note:'Open-source R tools for reading metadata, meshes, and skeletons. This application reads the documented public data directly; it does not incorporate R package code. The dataset has its own CC BY license.'},
 {id:'cx',title:'A connectome of the Drosophila central complex',authors:'Hulse et al. · eLife · 2021',url:'https://elifesciences.org/articles/66039',note:'Circuit organization of the central complex, including heading representation, navigation, and the pathways linking its component neuropils.'},
 {id:'memory',title:'The neuronal architecture of the mushroom body',authors:'Aso et al. · eLife · 2014',url:'https://elifesciences.org/articles/04577',note:'Kenyon cells, mushroom body compartments, dopaminergic inputs, and output neurons underlying associative learning.'},
 {id:'olfaction',title:'Information flow, cell types and stereotypy in a full olfactory connectome',authors:'Schlegel et al. · eLife · 2021',url:'https://elifesciences.org/articles/66018',note:'The organization of olfactory pathways through the antennal lobes, mushroom bodies, and lateral horn.'},
 {id:'vision',title:'Neuronal parts list and wiring diagram for a visual system',authors:'Matsliah et al. · Nature · 2024',url:'https://www.nature.com/articles/s41586-024-07981-1',note:'Cell types and circuitry of the adult fly optic lobe, supporting the distinction between early visual processing and higher visual pathways.'},
 {id:'body',title:'NeuroMechFly, a neuromechanical model of adult Drosophila',authors:'Lobato-Rios et al. · Nature Methods · 2022',url:'https://www.nature.com/articles/s41592-022-01466-7',note:'The exterior is the micro-CT-derived NeuroMechFly model distributed with FlyGym v1.2.1 (Apache 2.0). Its 69 placed components retain 502,781 source triangles. Pose and dark materials are illustrative; the body and brain are different specimens.'},
 {id:'tissue',title:'Ex vivo Whole-cell Recordings in Adult Drosophila Brain',authors:'Roemmich, Schutte & O’Dowd · Bio-protocol · 2018',url:'https://bio-protocol.org/en/bpdetail?id=2467&type=0',note:'The dissection protocol describes the brain as milky gray under a dissecting microscope, with bright white connective tissue. Natural tissue mode uses this description as a visual reference, not as calibrated color data for the source specimen.'},
];
export const GROUPS=[
 {id:'optic',name:'Optic lobes',color:'#9daee8',subtitle:'Vision'},
 {id:'mushroom',name:'Mushroom bodies',color:'#eaa88f',subtitle:'Learning & memory'},
 {id:'central',name:'Central complex',color:'#edcc7a',subtitle:'Orientation & navigation'},
 {id:'olfactory',name:'Olfactory regions',color:'#b3cd95',subtitle:'Odor processing'},
 {id:'lateral',name:'Lateral neuropils',color:'#a59bd0',subtitle:'Sensory integration'},
 {id:'superior',name:'Superior neuropils',color:'#c398ae',subtitle:'Higher-order circuits'},
 {id:'inferior',name:'Inferior neuropils',color:'#89beba',subtitle:'Central integration'},
 {id:'ventral',name:'Ventral & gnathal',color:'#d6b69a',subtitle:'Sensory–motor pathways'},
] as const;
export type GroupId=typeof GROUPS[number]['id'];
type Definition={name:string;group:GroupId;summary:string;detail:string;source:string};
const d=(name:string,group:GroupId,summary:string,detail:string,source='ito'):Definition=>({name,group,summary,detail,source});
export const DEFINITIONS:Record<string,Definition>={
 MB_A:d('Mushroom body · α lobe','mushroom','The vertical branch of α/β Kenyon-cell axons.','MaleCNS distinguishes this lobe from α′ and from the medial β lobe. The region contains compartmentalized interactions with dopaminergic inputs and mushroom body output neurons.','memory'),
 MB_AP:d('Mushroom body · α′ lobe','mushroom','The vertical branch of α′/β′ Kenyon-cell axons.','This native surface follows the α′ lobe territory. Its partner β′ branch extends medially; individual learning compartments are smaller than the displayed region.','memory'),
 MB_B:d('Mushroom body · β lobe','mushroom','The medial branch of α/β Kenyon-cell axons.','The α/β system bifurcates into vertical α and medial β branches. This source resolves the β territory independently.','memory'),
 MB_BP:d('Mushroom body · β′ lobe','mushroom','The medial branch of α′/β′ Kenyon-cell axons.','This surface marks the β′ lobe, distinct from β and γ. Compartmental circuitry supports experience-dependent changes in mushroom body output.','memory'),
 MB_G:d('Mushroom body · γ lobe','mushroom','The medial lobe occupied by γ Kenyon-cell axons.','γ Kenyon cells form a distinct mushroom body population. The lobe contains multiple dopaminergic and output-neuron compartments; its surface is a regional boundary.','memory'),
 AB:d('Asymmetric body','central','A paired neuropil with unequal left and right morphology.','MaleCNS provides separate left and right source surfaces. The region is associated with the central complex; its name refers to anatomical asymmetry.','cx'),
 LA:d('Lamina','optic','The first optic neuropil behind the compound eye.','Retinal photoreceptors R1–R6 terminate in repeating cartridges here. The surface marks the region as a whole; individual cartridges are not resolved.','vision'),
 ME:d('Medulla','optic','A layered hub of early visual computation.','The medulla lies between the lamina and lobula complex. Its columnar organization preserves visual position while local circuits process contrast, color, and motion-related signals. The ten layers are contained inside this regional boundary.','vision'),
 LO:d('Lobula','optic','A visual neuropil that helps extract features from the scene.','Lobula circuits receive processed visual input and project toward central brain regions. Different cell types encode distinct visual features; the entire lobula does not have one exclusive function.','vision'),
 LOP:d('Lobula plate','optic','A major center for wide-field visual motion.','Direction-selective inputs and large tangential neurons support responses to optic flow, including stabilization and steering. It lies beside the lobula within the optic lobe.','vision'),
 AME:d('Accessory medulla','optic','A small neuropil at the medial edge of the optic lobe.','This compact region is associated with circadian clock circuitry and light-related signaling. It is anatomically distinct from the much larger medulla.','annotation'),
 MB_CA:d('Mushroom body · calyx','mushroom','The input region of the mushroom body.','Kenyon-cell dendrites receive projection-neuron input in the calyx. Odor representations are a major input, while some Kenyon cells also receive other sensory modalities. The cup-shaped boundary does not depict individual synapses.','memory'),
 MB_PED:d('Mushroom body · peduncle','mushroom','The axonal stalk linking the calyx to the lobes.','Kenyon-cell axons travel together through the peduncle before continuing into mushroom body lobes. Its narrow shape makes it easier to inspect in the isolated view.','memory'),
 MB_VL:d('Mushroom body · vertical lobe','mushroom','The upward-projecting mushroom body lobe territory.','This atlas groups vertical lobe territory rather than exposing every α and α′ compartment. Kenyon-cell axons interact with dopaminergic inputs and output neurons in spatially organized learning circuits.','memory'),
 MB_ML:d('Mushroom body · medial lobe','mushroom','Mushroom body lobe territory extending toward the midline.','This source groups medial lobe territory rather than separating every β, β′, and γ compartment. Experience changes signaling within mushroom body circuits, influencing later behavioral choices.','memory'),
 EB:d('Ellipsoid body','central','A ring-shaped component of the central complex.','Recurrent circuitry here supports an internal representation of heading. Its relationship to the protocerebral bridge is central to the fly’s orientation system. The ring surface is an anatomical boundary, not a display of current neural activity.','cx'),
 FB:d('Fan-shaped body','central','A layered midline neuropil linking heading, movement, and internal state.','Columnar and tangential neurons meet in the fan-shaped body. Its circuits participate in navigation and integrate multiple signals. The native surface encloses its layers without individually segmenting them.','cx'),
 PB:d('Protocerebral bridge','central','An arched, segmented neuropil spanning the dorsal midline.','Bridge circuits connect with the ellipsoid body, fan-shaped body, and noduli. Repeated subdivisions are part of the organization of heading and navigation circuits; this mesh shows the combined bridge.','cx'),
 NO:d('Noduli','central','The paired ventral component of the central complex.','The source represents both noduli with one region identifier. Their circuits convey movement-related information to other central complex neuropils. One selectable mesh can therefore include paired anatomy.','cx'),
 AL:d('Antennal lobe','olfactory','The first major olfactory processing center in the brain.','Sensory neurons from the antennae and maxillary palps converge in glomeruli. Local neurons reshape these signals; projection neurons carry them toward the mushroom body and lateral horn. Glomeruli are not separately segmented here.','olfaction'),
 LH:d('Lateral horn','olfactory','A higher olfactory region involved in odor-guided behavior.','Projection neurons carry antennal-lobe output into lateral horn circuits. These pathways contribute to innate responses and interact with learning-related pathways; this is not a strict separation between innate and learned behavior.','olfaction'),
 BU:d('Bulb','central','A relay associated with visual input to the central complex.','Bulb microglomeruli participate in pathways from the anterior optic tubercle toward ellipsoid-body ring neurons. The bulbs are adjacent to, but are not core components of, the central complex.','cx'),
 LAL:d('Lateral accessory lobe','central','A region linking central complex circuits with wider brain pathways.','The lateral accessory lobe is important in the broader network connecting navigation computations with action. It is grouped here with associated central complex regions for exploration.','cx'),
 GA:d('Gall','central','A small neuropil associated with ellipsoid-body circuitry.','The gall is included with central complex-associated regions in this interface. Its compact source boundary is best examined in isolation.','cx'),
 AOTU:d('Anterior optic tubercle','lateral','A distinct anterior visual relay in the central brain.','It receives visual pathways and participates in routes toward the bulb and central complex. The single regional surface does not separate its finer subdivisions.','cx'),
 AVLP:d('Anterior ventrolateral protocerebrum','lateral','The anterior part of the ventrolateral neuropils.','This is a broad territory containing multiple neuronal populations, including visual and other sensory pathways. The label identifies anatomy, rather than assigning one behavior to the entire region.','annotation'),
 PVLP:d('Posterior ventrolateral protocerebrum','lateral','A posterior territory of the ventrolateral neuropils.','Visual projection pathways enter lateral central-brain regions from the optic lobes. This source boundary separates PVLP from the neighboring anterior territory.','annotation'),
 PLP:d('Posterior lateral protocerebrum','lateral','A posterior lateral region of the central brain.','The PLP is a named anatomical territory containing diverse circuits. Its broad surface should not be interpreted as a single functional module.','annotation'),
 WED:d('Wedge','lateral','A wedge-shaped region of the ventrolateral brain.','The wedge lies among neighboring lateral and ventral neuropils. Use the source region name to cross-reference specific cell types; the regional mesh alone does not establish their function.','annotation'),
 SLP:d('Superior lateral protocerebrum','superior','A dorsal lateral territory of the central brain.','The superior neuropils contain extensive arborizations from diverse neuron types. SLP is distinguished spatially from the superior intermediate and superior medial regions.','annotation'),
 SIP:d('Superior intermediate protocerebrum','superior','The intermediate territory of the superior neuropils.','This named region lies between superior lateral and medial territories. Its border is an atlas segmentation of neuropil, not a membrane between organs.','annotation'),
 SMP:d('Superior medial protocerebrum','superior','The medial territory of the superior neuropils.','Its position near the dorsal midline places it around central brain circuits. Many neuron classes arborize here; no single cognitive function describes the entire region.','annotation'),
 SCL:d('Superior clamp','inferior','A dorsal subdivision of the clamp surrounding mushroom body territory.','Clamp names describe the relationship of surrounding neuropil to the mushroom body. The superior clamp is distinct from the inferior clamp in the source atlas.'),
 ICL:d('Inferior clamp','inferior','An inferior subdivision of the neuropil around the mushroom body.','The surface delineates a spatially defined neuropil domain. Exploding it reveals its shape relative to nearby mushroom body structures.'),
 CRE:d('Crepine','inferior','A central neuropil surrounding the mushroom body peduncle.','The crepine is an anatomical territory rather than a tract. Its close relationship to the peduncle is easiest to see with other regions hidden.'),
 IB:d('Inferior bridge','inferior','A named inferior region of the central brain.','The inferior bridge is distinct from the protocerebral bridge of the central complex. Similar wording does not imply the same structure or circuitry.'),
 ATL:d('Antler','inferior','A small named neuropil in the central brain.','This region is identified by its characteristic morphology and position in the anatomical nomenclature. Its mesh provides regional context for neuronal arborizations.'),
 CAN:d('Cantle','inferior','A named neuropil near the posterior central brain.','The cantle is a spatially defined territory. The source segmentation supports inspection of its boundary, but not a single exclusive functional interpretation.'),
 FLA:d('Flange','inferior','A small central-brain neuropil domain.','The flange is one of the named compartments of the inferior neuropils. This compact regional surface is retained as an individually selectable part.'),
 IPS:d('Inferior posterior slope','ventral','The inferior part of the posterior slope.','Posterior-slope territories participate in wider sensory–motor networks. This atlas retains IPS separately from the superior posterior slope.','annotation'),
 SPS:d('Superior posterior slope','ventral','The superior part of the posterior slope.','The source separates this territory from the inferior posterior slope. Regional boundaries provide context for diverse ascending, descending, and intrinsic neurons.','annotation'),
 VES:d('Vest','ventral','A ventromedial neuropil territory.','The vest is anatomically defined within the ventromedial brain. Its shape and location are preserved from the MaleCNS region mesh.'),
 EPA:d('Epaulette','ventral','A named ventromedial neuropil domain.','The epaulette is a compact regional compartment near other ventromedial neuropils. Its individual boundary is retained for anatomical comparison.'),
 GOR:d('Gorget','ventral','A medial neuropil territory near the esophageal region.','The gorget is part of the named ventromedial neuropils. It is displayed separately from nearby vest and epaulette regions.'),
 AMMC:d('Antennal mechanosensory and motor center','ventral','An early processing region for antennal mechanical signals.','Inputs include Johnston’s organ pathways associated with antennal movement and vibration. This is distinct from the odor-processing antennal lobe.','annotation'),
 GNG:d('Gnathal ganglia','ventral','Ventral brain territory associated with mouthpart and feeding circuits.','The gnathal ganglia include fused segmental territories beneath the cerebral brain. The displayed surface is a combined region, not individual mouthpart motor nuclei.','annotation'),
 PRW:d('Prow','ventral','An anterior neuropil near the esophageal region.','The prow belongs to the periesophageal neuropils in the anatomical nomenclature. It provides regional context for ventral sensory–motor circuitry.'),
 SAD:d('Saddle','ventral','A neuropil surrounding part of the esophageal passage.','The saddle is a named periesophageal region. Its boundary is kept distinct from the neighboring prow and gnathal territory.'),
 OCG:d('Ocellar ganglion','optic','Neuropil associated with the simple eyes, or ocelli.','The ocelli are distinct from the large compound eyes. This midline region is retained alongside the compound-eye optic neuropils.','annotation'),
};
export interface Part {id:string;sourceId:number;vertices:number;triangles:number;bounds:[number[],number[]];sha256:string;url:string}
export interface Atlas {source:string;parts:Part[]}
export const baseId=(id:string)=>id.replace(/_[LR]$/,'');
export const definition=(id:string)=>DEFINITIONS[baseId(id)];
export const side=(id:string)=>id.endsWith('_L')?'Left':id.endsWith('_R')?'Right':'Midline / combined';
export const groupFor=(id:string)=>GROUPS.find(g=>g.id===definition(id).group)!;
export type ViewerState={hoveredGroup?:GroupId|null;mode:'brain'|'cells'|'fly';explode:number;visible:GroupId[];selected:string|null;isolate:boolean;rotate:boolean;labels:boolean;surface:'atlas'|'tissue'|'glass';meshLines:boolean;view:'anterior'|'posterior'|'dorsal'|'lateral';reset:number};

export const pairedId=(id:string)=>id.endsWith('_L')?id.slice(0,-2)+'_R':id.endsWith('_R')?id.slice(0,-2)+'_L':id;
